name: PinLoc
main: com.objecteffects.pinloc.plugin.PinLoc
version: 0.0.1-SNAPSHOT
author: rusty@gmail.com
commands:
  pinloc:
    description: Place a pin at (remember) this location.
    usage: /pinloc
    permission: PinLoc.basic
    permission-message: You do not have <permission>